const text=(selector,value)=>{const node=document.querySelector(selector);if(node)node.textContent=value;};
const safe=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const reader=document.querySelector('#reader');let lastTrigger;
function openArticle(article,author){lastTrigger=document.activeElement;text('#reader-title',article.title);text('#reader-category',article.category);text('.reader-meta',`${author} · ${article.date}`);document.querySelector('#reader-body').innerHTML=article.blocks.map(b=>b.type==='h2'?`<h3>${safe(b.text)}</h3>`:b.type==='quote'?`<blockquote>${safe(b.text)}</blockquote>`:b.type==='list'?`<ul>${b.text.split('\n').filter(Boolean).map(line=>`<li>${safe(line)}</li>`).join('')}</ul>`:`<p>${safe(b.text).replaceAll('\n','<br>')}</p>`).join('');reader.showModal();reader.scrollTop=0;document.body.classList.add('reading');}
function render(content){const {site,articles,project}=content;document.title=`${site.name} — ${site.author}`;document.querySelector('meta[name="description"]').content=site.intro.replaceAll('\n',' ');document.querySelector('.brand').setAttribute('aria-label',`${site.name}首页`);document.querySelector('.brand').innerHTML=`<span class="brand-symbol">c.</span><span>${safe(site.name)}<small>JUST FOUND THE WORDS</small></span>`;document.querySelector('.intro>.eyebrow').innerHTML=`${safe(site.author)}’S PERSONAL JOURNAL <span>VOL. 01 / 2026</span>`;document.querySelector('h1').innerHTML=`${safe(site.hero1)}<br><span class="italic">${safe(site.hero2)}</span>`;document.querySelector('.intro-aside>p').innerHTML=safe(site.intro).replaceAll('\n','<br>');
const featured=articles.find(a=>a.id===content.featuredId)||articles[0];text('.feature h2',featured.title);text('.feature-copy>p',featured.excerpt);text('.feature-copy .meta',`${featured.date.replaceAll('-','.')} · ${featured.category}`);for(const button of document.querySelectorAll('.feature button')){button.onclick=()=>openArticle(featured,site.author);if(button.classList.contains('feature-cover'))button.setAttribute('aria-label',`阅读：${featured.title}`);}
document.querySelector('#journal .count').textContent=`${articles.length} 篇文字`;document.querySelectorAll('.article-row').forEach(e=>e.remove());for(const a of articles.filter(a=>a.id!==featured.id).sort((a,b)=>b.date.localeCompare(a.date))){const button=document.createElement('button');button.className='article-row';button.innerHTML=`<span class="article-date">${safe(a.date.slice(5).replace('-','.'))}<small>${safe(a.date.slice(0,4))}</small></span><div><span class="category">${safe(a.category)}</span><h3>${safe(a.title)}</h3><p>${safe(a.excerpt)}</p></div><span class="row-arrow" aria-hidden="true">↗</span>`;button.onclick=()=>openArticle(a,site.author);document.querySelector('#journal').append(button);}
text('.project-type',project.name);text('.project h3',project.title);text('.project>p',project.description);text('.marginalia>p',`“${project.note}”`);const oldProject=document.querySelector('button.project');if(oldProject){const replacement=document.createElement('div');replacement.className='project';replacement.innerHTML=oldProject.innerHTML;oldProject.replaceWith(replacement);}text('#about h2',`你好，这里是${site.name}。`);document.querySelector('#about>div>p').innerHTML=safe(site.about).replaceAll('\n','<br>');text('.signature',site.author);const notes=document.querySelectorAll('.now>p');notes[0].innerHTML=`<span>在做</span>${safe(site.nowDoing)}`;notes[1].innerHTML=`<span>在想</span>${safe(site.nowThinking)}`;text('footer>span',`© ${new Date().getFullYear()} ${site.name} · ${site.author}`);text('.reader-bar>span',`${site.name} / THE JOURNAL`);text('.reader-end','写在这里，留待下次。');document.querySelector('.demo-note')?.remove();}
document.querySelector('#close-reader').onclick=()=>reader.close();reader.addEventListener('close',()=>{document.body.classList.remove('reading');lastTrigger?.focus();});reader.addEventListener('click',e=>{if(e.target===reader){const r=reader.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)reader.close();}});
try{const r=await fetch('./content.json',{cache:'no-cache'});if(!r.ok)throw Error('Content unavailable');render(await r.json());}catch(error){document.querySelectorAll('[data-article]').forEach(b=>b.disabled=true);const p=document.createElement('p');p.className='content-error';p.setAttribute('role','alert');p.textContent='文章暂时未能加载，请刷新页面重试。';document.querySelector('.intro').append(p);}
